### ISSUE TITLE
Fix uncoordinated swerve module

### ISSUE THREAD

**Issue by jkleiber** [team401/2023-Robot-Code#4]
**Summary**
It has been reported that one of the swerve modules can become uncoordinated from the other three, which leads to undesirable driving.

The objective of this ticket is to investigate and fix the underlying problem that leads to uncoordinated driving.

**Possible Causes**
- Encoder losing power somehow results in position reset
- CANCoder "freezes" leading to wheel being dragged along

**Ruled out**
- Anything related to the relative encoder - the CANCoder is set to absolute mode at Init time.

**Work Required**
- Determine root cause of swerve module positioning issue
- Fix the problem (TBD)

**Verification**
- Code Review
- Driver practice

FYI: @redPlover @FujiBookPro

**Comment by redPlover** [comment]
I apologize for that (and for spamming with notifications), I accidentally closed the issue with a comment. I meant to ask: We don't use a relative encoder, should we add one?

**Comment by jkleiber** [comment]
Good point, the encoder is clearly in absolute mode in the code. I'll update this to include a more open ended investigation into the problem. Do we have any data / anecdotal evidence about what happens and potential root causes?

**Comment by redPlover** [comment]
My guess is that the CANCoder freezes. Maybe we could use the motor's relative encoder for redundancy?

**Comment by jkleiber** [comment]
Something worth checking is if the CANCoder defaults to 0 on boot or if it defaults to the absolute encoder position: https://v5.docs.ctr-electronics.com/en/stable/ch12a_BringUpCANCoder.html#choose-sensor-boot-initialization-strategy

If it defaults to 0, this could be as simple as setting it to default to the absolute encoder position in the firmware

**Comment by redPlover** [comment]
Swerve module seems to work now after switching CANCoder defaults to the absolute encoder position.
