### ISSUE TITLE
Create release candidate for Blue Ridge Brawl

### ISSUE THREAD

**Issue by jkleiber** [team401/2023-Robot-Code#5]
**Summary**
We should cut a release branch (for use in competition as needed) and tag a release on Github for our official BRB code. This will allow us to continue development without worrying about regressions prior to competition.

**Work Required**
- Make a release branch off of main once BRB code is finalized
- Tag a release on Github

**Comment by redPlover** [comment]
Release created in baseline/BRB-Comp
