### ISSUE TITLE
Create test plan for finding feedforward parameters of the arm and wrist

### ISSUE THREAD

**Issue by jkleiber** [team401/2023-Robot-Code#9]
**Summary**
The tuning process for the wrist could use additional documentation. More importantly, it would be way more efficient to automate the process of finding kG, kS, kA and kV. Before writing some commands to do this, it would be best to define what the process will be for finding each constant. It would be good to do this for the arm as well.

**Work Scope**
- Create a test plan document (google drive, or a README.md in the repo, or maybe a Wiki item in the repo) that details the process of finding kG, kS, kA and kV for the wrist
- Create a similar document for the arm

**Verification**
- Peer review

**Comment by redPlover** [comment]
Done here (in shared Google Drive):
[https://docs.google.com/drawings/d/1dQqgLizTVJ802iVc2zNO-VQKmRVe7FS54vzymxd_D-c/edit?usp=sharing](url)
